// Package docs code generated by oapi sdk gen
/*
 * MIT License
 *
 * Copyright (c) 2022 Lark Technologies Pte. Ltd.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice, shall be included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
 */

package larkdocs

import (
	"fmt"

	"github.com/larksuite/oapi-sdk-go/v3/core"
)

const (
	DocTypeDOCX = "docx" // 新版文档
)

const (
	ContentTypeMarkdown = "markdown" // Markdown 格式
)

const (
	LangZH = "zh" // 中文
	LangEN = "en" // 英文
	LangJA = "ja" // 日文
)

type DepartmentId struct {
	DepartmentId *string `json:"department_id,omitempty"` //

	OpenDepartmentId *string `json:"open_department_id,omitempty"` //
}

type DepartmentIdBuilder struct {
	departmentId     string //
	departmentIdFlag bool

	openDepartmentId     string //
	openDepartmentIdFlag bool
}

func NewDepartmentIdBuilder() *DepartmentIdBuilder {
	builder := &DepartmentIdBuilder{}
	return builder
}

// 示例值：
func (builder *DepartmentIdBuilder) DepartmentId(departmentId string) *DepartmentIdBuilder {
	builder.departmentId = departmentId
	builder.departmentIdFlag = true
	return builder
}

// 示例值：
func (builder *DepartmentIdBuilder) OpenDepartmentId(openDepartmentId string) *DepartmentIdBuilder {
	builder.openDepartmentId = openDepartmentId
	builder.openDepartmentIdFlag = true
	return builder
}

func (builder *DepartmentIdBuilder) Build() *DepartmentId {
	req := &DepartmentId{}
	if builder.departmentIdFlag {
		req.DepartmentId = &builder.departmentId

	}
	if builder.openDepartmentIdFlag {
		req.OpenDepartmentId = &builder.openDepartmentId

	}
	return req
}

type Meta struct {
	DocToken *string `json:"doc_token,omitempty"` // 文档 Token

	DocType *string `json:"doc_type,omitempty"` // 文档类型

	Title *string `json:"title,omitempty"` // 标题

	OwnerId *string `json:"owner_id,omitempty"` // 文档所有者

	LatestModifyUser *string `json:"latest_modify_user,omitempty"` // 最后编辑者

	LatestModifyTime *string `json:"latest_modify_time,omitempty"` // 最后编辑时间（Unix 时间戳）

	Url *string `json:"url,omitempty"` // 文档链接

	SecLabelName *string `json:"sec_label_name,omitempty"` // 文档密级标签名称
}

type MetaBuilder struct {
	docToken     string // 文档 Token
	docTokenFlag bool

	docType     string // 文档类型
	docTypeFlag bool

	title     string // 标题
	titleFlag bool

	ownerId     string // 文档所有者
	ownerIdFlag bool

	latestModifyUser     string // 最后编辑者
	latestModifyUserFlag bool

	latestModifyTime     string // 最后编辑时间（Unix 时间戳）
	latestModifyTimeFlag bool

	url     string // 文档链接
	urlFlag bool

	secLabelName     string // 文档密级标签名称
	secLabelNameFlag bool
}

func NewMetaBuilder() *MetaBuilder {
	builder := &MetaBuilder{}
	return builder
}

// 文档 Token
//
// 示例值：doccnfYZzTlvXqZIGTdAHKabcef
func (builder *MetaBuilder) DocToken(docToken string) *MetaBuilder {
	builder.docToken = docToken
	builder.docTokenFlag = true
	return builder
}

// 文档类型
//
// 示例值：docx
func (builder *MetaBuilder) DocType(docType string) *MetaBuilder {
	builder.docType = docType
	builder.docTypeFlag = true
	return builder
}

// 标题
//
// 示例值：sampletitle
func (builder *MetaBuilder) Title(title string) *MetaBuilder {
	builder.title = title
	builder.titleFlag = true
	return builder
}

// 文档所有者
//
// 示例值：ou_b13d41c02edc52ce66aaae67bf1abcef
func (builder *MetaBuilder) OwnerId(ownerId string) *MetaBuilder {
	builder.ownerId = ownerId
	builder.ownerIdFlag = true
	return builder
}

// 最后编辑者
//
// 示例值：ou_b13d41c02edc52ce66aaae67bf1abcef
func (builder *MetaBuilder) LatestModifyUser(latestModifyUser string) *MetaBuilder {
	builder.latestModifyUser = latestModifyUser
	builder.latestModifyUserFlag = true
	return builder
}

// 最后编辑时间（Unix 时间戳）
//
// 示例值：1652066345
func (builder *MetaBuilder) LatestModifyTime(latestModifyTime string) *MetaBuilder {
	builder.latestModifyTime = latestModifyTime
	builder.latestModifyTimeFlag = true
	return builder
}

// 文档链接
//
// 示例值：https://sample.feishu.cn/docs/doccnfYZzTlvXqZIGTdAHKabcef
func (builder *MetaBuilder) Url(url string) *MetaBuilder {
	builder.url = url
	builder.urlFlag = true
	return builder
}

// 文档密级标签名称
//
// 示例值：L2-内部
func (builder *MetaBuilder) SecLabelName(secLabelName string) *MetaBuilder {
	builder.secLabelName = secLabelName
	builder.secLabelNameFlag = true
	return builder
}

func (builder *MetaBuilder) Build() *Meta {
	req := &Meta{}
	if builder.docTokenFlag {
		req.DocToken = &builder.docToken

	}
	if builder.docTypeFlag {
		req.DocType = &builder.docType

	}
	if builder.titleFlag {
		req.Title = &builder.title

	}
	if builder.ownerIdFlag {
		req.OwnerId = &builder.ownerId

	}
	if builder.latestModifyUserFlag {
		req.LatestModifyUser = &builder.latestModifyUser

	}
	if builder.latestModifyTimeFlag {
		req.LatestModifyTime = &builder.latestModifyTime

	}
	if builder.urlFlag {
		req.Url = &builder.url

	}
	if builder.secLabelNameFlag {
		req.SecLabelName = &builder.secLabelName

	}
	return req
}

type GetContentReqBuilder struct {
	apiReq *larkcore.ApiReq
}

func NewGetContentReqBuilder() *GetContentReqBuilder {
	builder := &GetContentReqBuilder{}
	builder.apiReq = &larkcore.ApiReq{
		PathParams:  larkcore.PathParams{},
		QueryParams: larkcore.QueryParams{},
	}
	return builder
}

// 文档唯一标识
//
// 示例值：B4EPdAYx8oi8HRxgPQQbM15UcBf
func (builder *GetContentReqBuilder) DocToken(docToken string) *GetContentReqBuilder {
	builder.apiReq.QueryParams.Set("doc_token", fmt.Sprint(docToken))
	return builder
}

// 文档类型
//
// 示例值：docx
func (builder *GetContentReqBuilder) DocType(docType string) *GetContentReqBuilder {
	builder.apiReq.QueryParams.Set("doc_type", fmt.Sprint(docType))
	return builder
}

// 内容类型
//
// 示例值：markdown
func (builder *GetContentReqBuilder) ContentType(contentType string) *GetContentReqBuilder {
	builder.apiReq.QueryParams.Set("content_type", fmt.Sprint(contentType))
	return builder
}

// 语言
//
// 示例值：zh
func (builder *GetContentReqBuilder) Lang(lang string) *GetContentReqBuilder {
	builder.apiReq.QueryParams.Set("lang", fmt.Sprint(lang))
	return builder
}

func (builder *GetContentReqBuilder) Build() *GetContentReq {
	req := &GetContentReq{}
	req.apiReq = &larkcore.ApiReq{}
	req.apiReq.QueryParams = builder.apiReq.QueryParams
	return req
}

type GetContentReq struct {
	apiReq *larkcore.ApiReq
}

type GetContentRespData struct {
	Content *string `json:"content,omitempty"` // 内容
}

type GetContentResp struct {
	*larkcore.ApiResp `json:"-"`
	larkcore.CodeError
	Data *GetContentRespData `json:"data"` // 业务数据
}

func (resp *GetContentResp) Success() bool {
	return resp.Code == 0
}
